export const projectsData = [
  {
    id: 1,
    title: "Social Media",
    description:
      "Uma rede social feito utilizando TypeScript, React, Appwrite e +",
    image: "https://utfs.io/f/b34721b0-cdb1-4722-86f7-f0b3017effd1-lbpkzo.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/social-media",
    previewUrl: "https://social-media-plum-three.vercel.app/",
  },
  {
    id: 2,
    title: "E-commerce ECD",
    description:
      "E-commerce desenvolvido com NextJs, Typescript, Postgres, PrismaORM e +",
    image: "https://utfs.io/f/cf47db19-f41d-4772-af14-40566abe94f0-le3xoj.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/e-commerce",
    previewUrl: "https://e-commerce-daniilomendes-projects.vercel.app/",
  },
  {
    id: 3,
    title: "FSW Foods",
    description:
      "E-commerce desenvolvido com NextJs, Typescript, Postgres, PrismaORM e +",
    image: "https://utfs.io/f/9c149bbe-a0f3-4d79-abfa-3ae82cda3bfb-1tn2mr.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/fsw-foods",

    previewUrl: "https://fsw-foods-daniilomendes-projects.vercel.app/",
  },
  {
    id: 4,
    title: "Blog",
    description:
      "Um blog feito utilizando API Node, Javascript, React, MongoDb e +",
    image: "https://utfs.io/f/a9a1dd42-3e81-4248-ab3e-0fcfb6220f86-86w4ga.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/blog",
    previewUrl: "https://blog-zvn5.onrender.com",
  },
  {
    id: 5,
    title: "Menu Online",
    description: "O Menu de lanches feito apenas com HTML, CSS e Javascript",
    image: "https://utfs.io/f/0821f123-f8a5-4d50-a57a-d49015a99a8e-1zr6n.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/site_de_vendas_lanches",
    previewUrl: "https://incandescent-moxie-19bd07.netlify.app",
  },
  {
    id: 6,
    title: "Controle Financeiro",
    description: "Controle seus gastos feito com uma API GraphQl, React e +",
    image: "https://utfs.io/f/050702dd-d9c1-4bea-8537-548a1163cb83-4o7z25.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/expense-tracker-graphql",
    previewUrl: "https://expense-tracker-graphql-peva.onrender.com/",
  },
  {
    id: 7,
    title: "KanBan App",
    description:
      "Organize seus afazeres com esta aplicação feita com React e Drag-and-drop",
    image: "https://utfs.io/f/199ed1a8-7818-4c53-b59e-606f406f3f38-eg2iq2.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/kanban-app",
    previewUrl: "https://chic-torte-7dabe0.netlify.app",
  },
  {
    id: 8,
    title: "Youtube clone",
    description:
      "Clonando o Youtube utilizando React e a Api do Youtube encontrada no RapidApi",
    image: "https://utfs.io/f/c05eb9ed-81c3-4f44-890d-e28c4ca907e1-x2mz4d.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/youtube-clone",
    previewUrl: "https://timely-sopapillas-93d31c.netlify.app/",
  },
  {
    id: 9,
    title: "Temporizadores",
    description:
      "Adicione diversos temporizadores com está aplicação feita com React e Typescript",
    image: "https://utfs.io/f/daaa2301-ba46-48d8-bdf6-250b798c8ec4-4dpigs.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/timer-app-react-ts",
    previewUrl: "https://dashing-tapioca-083d6e.netlify.app",
  },
  {
    id: 10,
    title: "Mini Shop com Redux",
    description:
      "Calcule o quanto vai gastar nesse app feito com React, Redux e Typescript",
    image: "https://utfs.io/f/c481d051-929b-4650-9c06-cb1557329577-31mlev.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/shop-app-redux-react-ts",
    previewUrl: "https://harmonious-palmier-eaff12.netlify.app",
  },
  {
    id: 11,
    title: "Anote suas Metas",
    description:
      "Anote suas metas, mas ele te avisa quando excede-las, feito com React e Typescript",
    image: "https://utfs.io/f/e2aeaf31-9377-4629-8526-1d675e51be58-v0l5i3.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/goals-app-react-ts",
    previewUrl: "https://imaginative-scone-36a954.netlify.app",
  },
  {
    id: 12,
    title: "Resumidor de Artigos",
    description:
      "Resuma seus artigos utilizando esta Api Resumidora, feito com React e Javascript",
    image: "https://utfs.io/f/1242d4bb-bba2-4a2c-b4fc-d6e5ca3b2021-ticoi6.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/api_ia_resumidor",
    previewUrl: "https://comfy-mousse-2932bb.netlify.app/",
  },
  {
    id: 13,
    title: "Gestor de Estoque",
    description:
      "Adicione e calcule seu estoque com está aplicação feita em React",
    image: "https://utfs.io/f/7d0e6bab-68ae-4962-950b-3a229ac641bf-ge4cj7.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/gestor-de-estoque",
    previewUrl: "https://stupendous-alpaca-ebe272.netlify.app/",
  },
  {
    id: 14,
    title: "Calculadora",
    description:
      "Uma calculadora com modo noturno/claro criada com HTML, CSS e Javascript",
    image: "https://utfs.io/f/7106ca2e-b682-4578-876b-173d44c105d4-fgrl8x.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/calculadora-normal",
    previewUrl: "https://willowy-scone-0f20f8.netlify.app/",
  },
  {
    id: 15,
    title: "Vitrine de Carros",
    description:
      "Pesquise sobre os melhores veículos com está Api de Carros, feito com React",
    image: "https://utfs.io/f/d1b7f0fc-0ee7-4d5b-9931-8f17df75b7b5-soita8.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/vitrini_de_carros",
    previewUrl: "https://coruscating-centaur-cb3cf8.netlify.app/",
  },
  {
    id: 16,
    title: "Quiz",
    description: "Teste seus conhecimentos com este Quiz feito com React",
    image: "https://utfs.io/f/cea7f678-57e0-4187-bd7a-89d34d92c798-22mvp.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/quiz_com_React",
    previewUrl: "https://animated-conkies-433c76.netlify.app/",
  },
  {
    id: 17,
    title: "Data Fetching Blog",
    description:
      "Recuperando informações da Api do Blog com React e Typescript",
    image: "https://utfs.io/f/fdf3c93f-252c-4a3f-8f99-fc88c162201a-sl99ea.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/data-fetching-react-ts",
    previewUrl: "https://silly-praline-449919.netlify.app",
  },
  {
    id: 18,
    title: "Jogo da Velha",
    description:
      "Se divirta com este jogo da velha feito com HTML, CSS e Javascript",
    image: "https://utfs.io/f/233176a2-e28a-4fdd-8942-f032190cec5c-z8c8za.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/jogo-da-velha",
    previewUrl: "https://splendorous-sprite-c66f9a.netlify.app/",
  },
  {
    id: 19,
    title: "Lista To Do",
    description:
      "Liste, filtre e conclua seus afazeres com este app feito com HTML, CSS e Javascript",
    image: "https://utfs.io/f/5b590e6e-1126-490c-bf81-283d27c8391b-1ts07x.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/lista_de_afazeres_ToDo",
    previewUrl: "https://magnificent-kelpie-a2ca22.netlify.app/",
  },
  {
    id: 20,
    title: "Localizador de GitHubs",
    description:
      "Localize os GitHubs utilizando está Api feita com React e Typescript",
    image: "https://utfs.io/f/9f4c6f5d-d5c0-4e16-b4a7-bb6f69e16477-pj8qxc.png",
    tag: ["Todos", "Web"],
    gitUrl:
      "https://github.com/daniilomendes/github_finder_com_React_e_TypeScript",
    previewUrl: "https://sparkling-bienenstitch-901450.netlify.app/",
  },
  {
    id: 21,
    title: "Notas Post-it",
    description:
      "Crie, anote e filtre diversos post-its, feita com HTML, CSS e Javascript ",
    image: "https://utfs.io/f/da40a5e4-20c1-4707-8230-82f383f8ce5e-rtgfsn.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/devnotes",
    previewUrl: "https://glistening-phoenix-5c72e7.netlify.app/",
  },
  {
    id: 22,
    title: "Pokedex",
    description:
      "Veja os detalhes dos pokemons nessa aplicação feita com React e JavaScript",
    image: "https://utfs.io/f/ccd68abf-e5d7-42ac-ad02-b6404c2b5afa-6lkuua.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes",
    previewUrl: "https://fascinating-blini-513ce6.netlify.app/",
  },
  {
    id: 23,
    title: "Tela de Login com Gerador de Senhas",
    description:
      "Gere uma senha personalizada, feito com HTML, CSS e Javascript",
    image: "https://utfs.io/f/9001f569-cf34-4466-9898-c95d2d87b7df-8nojov.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/gerador_de_senhas",
    previewUrl: "https://fancy-buttercream-402fcb.netlify.app/",
  },
  {
    id: 24,
    title: "Gerador de Qr-Code",
    description:
      "Gere QR-codes utilizando está aplicação feita com HTML, CSS e Javascript",
    image: "https://utfs.io/f/a5bfb53f-08c0-4564-a6f6-bb8f468c18b5-8gpr8a.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/gerador_qrcode",
    previewUrl: "https://bright-manatee-b711d0.netlify.app/",
  },
  {
    id: 25,
    title: "Dashboard",
    description: "UI/UX de um Dashboard completo feito com React",
    image: "https://utfs.io/f/af44742a-8651-4e23-9f44-2b1b8593c16b-l8o1dy.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/dashboard",
    previewUrl: "https://shimmering-starship-db869e.netlify.app/",
  },
  {
    id: 26,
    title: "Calculadora Simples",
    description: "Calculadora basica feita com HTML, CSS e Javascript",
    image: "https://utfs.io/f/40429b47-5fd5-4726-a944-8896cae4fecc-k28zqb.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/calculadora",
    previewUrl: "https://lighthearted-kataifi-7500ae.netlify.app/",
  },
  {
    id: 27,
    title: "Calculadora de IMC",
    description: "Calcule seu IMC com este site feito em React e Javascript",
    image: "https://utfs.io/f/51e0ae27-336f-4c85-b3c4-db0ede8f48b2-yo5dgf.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/calculadora_IMC_com_React",
    previewUrl: "https://fluffy-nasturtium-e06e48.netlify.app/",
  },
  {
    id: 28,
    title: "Gerador de Box Shadow",
    description:
      "Gere diversos box shadows de maneira rápida, feito com HTML, CSS e Javascript",
    image: "https://utfs.io/f/c31034ed-3bcf-480b-b699-dd04af96fd22-tfapwe.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/gerador_de_boxshadow",
    previewUrl: "https://chic-klepon-bea224.netlify.app/",
  },
  {
    id: 29,
    title: "Site de Acampamentos (UI/UX)",
    description:
      "UI/UX design de um site de viagens feito com React e Typescrip",
    image: "https://utfs.io/f/77b83094-cfce-4d6f-b764-8ff45c11306c-uizk3p.png",
    tag: ["Todos", "Web"],
    gitUrl: "https://github.com/daniilomendes/viagens-app",
    previewUrl: "https://brilliant-crumble-1b5796.netlify.app/",
  },
];
